[tool.poetry]
name = "django-telegram-bot-template"
version = "0.1.0"
description = ""
authors = ["Ilaletdinov Almaz <a.ilaletdinov@yandex.ru"]

[tool.poetry.dependencies]
python = "^3.10"
Django = "^5.0"
loguru = "^0.7"
pyTelegramBotAPI = "^4.2.0"
python-dotenv = "^1.0"
django-environ = "^0.11"
django-split-settings = "^1.1.0"
celery = "<5.0.0"
progressbar2 = "^4.4"

[tool.poetry.dev-dependencies]
flake8 = "^7.0"
flake8-eradicate = "^1.5"
flake8-isort = "^6.1"
flake8-print = "^5.0"
flake8-docstrings = "^1.6.0"
flake8-cognitive-complexity = "^0.1.0"
pytest = "^8.2"
pytest-django = "^4.8"
python-dateutil = "^2.8.1"
requests-mock = "^1.9.3"
pytest-cov = "^5.0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
