# Generated by Django 3.0.7 on 2020-06-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True, verbose_name='Дата отправки')),
                ('from_user_id', models.IntegerField(verbose_name='Идентификатор отправителя')),
                ('message_id', models.IntegerField(verbose_name='Идентификатор сообщения')),
                ('chat_id', models.IntegerField(verbose_name='Идентификатор чата, в котором идет общение')),
                ('text', models.TextField(null=True, verbose_name='Текст сообщения')),
                ('json', models.TextField()),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_chat_id', models.IntegerField(verbose_name='Идентификатор подписчика')),
                ('is_active', models.BooleanField(verbose_name='Подписан ли польователь на бота')),
                ('comment', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
            },
        ),
    ]
