# Generated by Django 3.0.7 on 2020-08-15 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Навзвание')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('key', models.CharField(max_length=128, verbose_name='Ключ, по которому сообщение вызывается в коде')),
            ],
            options={
                'verbose_name': 'Админитративное сообщение',
                'verbose_name_plural': 'Админитративные сообщения',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_chat_id', models.IntegerField(verbose_name='Идентификатор подписчика')),
                ('is_active', models.BooleanField(default=True, verbose_name='Подписан ли польователь на бота')),
                ('comment', models.TextField(null=True)),
                ('ref_info', models.CharField(max_length=128, null=True, verbose_name='Реферальный код')),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
            },
        ),
        migrations.CreateModel(
            name='SubscriberAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время')),
                ('action', models.CharField(choices=[('subscribed', 'подписался'), ('unsubscribed', 'отписался'), ('reactivated', 'реактивировался')], max_length=16, verbose_name='Действие')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_init.Subscriber', verbose_name='Подписчик')),
            ],
            options={
                'verbose_name': 'Действия пользователя',
                'verbose_name_plural': 'Действия пользователей',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True, verbose_name='Дата отправки')),
                ('from_user_id', models.IntegerField(verbose_name='Идентификатор отправителя')),
                ('message_id', models.IntegerField(verbose_name='Идентификатор сообщения')),
                ('chat_id', models.IntegerField(verbose_name='Идентификатор чата, в котором идет общение')),
                ('text', models.TextField(null=True, verbose_name='Текст сообщения')),
                ('json', models.TextField()),
                ('mailing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='bot_init.Mailing')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
